#!/bin/bash
#
# chkconfig: 345 95 5
# description: The ucx_chat service script
# process name: ucx_chat
#
# Author: Stephen Pallen
#

# Source function library.
. /etc/init.d/functions

PROG_NAME=ucx_chat
INSTALL_DIR=/var/www/$PROG_NAME
PROG=$INSTALL_DIR/bin/$PROG_NAME
RETVAl=0

txtgrn=$(tput setaf 2)
txtred=$(tput setaf 1)
txtrst=$(tput sgr0)

if [ -f /etc/sysconfig/$PROG_NAME ] ; then
  . /etc/sysconfig/$PROG_NAME
fi

[ -f $PROG ] || exit 0

message() {
  if [ $RETVAL -eq 0 ]; then
    printf "%-45s[${txtgrn}  OK  ${txtrst}]\n" "$1"
  else
    printf "%-45s[${txtred}FAILED${txtrst}]\n" "$1"
  fi
}
run() {
  HOME=$INSTALL_DIR $PROG $1 > /dev/null 2>&1
}

# run interactive. Don't redirect output
run_i() {
  HOME=$INSTALL_DIR $PROG $1
}

start() {
        run start
        RETVAL=$?
        message $"Starting $PROG_NAME: "
        return $RETVAL
}
stop() {
        run stop
        RETVAL=$?
        message "Stopping $PROG_NAME: "
        return $RETVAL
}
restart() {
        run restart
        RETVAL=$?
        message $"Restarting $PROG_NAME: "
        return $RETVAL
}
status() {
      run ping
      RETVAL=$?
      echo -n "Status: $PROG_NAME is "
      if [ $RETVAL -eq 0 ]; then
        echo "running ..."
      else
        echo "stopped"
      fi
      return $RETVAL
}
remote_console() {
      run_i remote_console
}
console() {
      run_i console
}

case "$1" in
        start)
          start
          RETVAL=$?
                ;;
        stop)
                stop
                ;;
        status)
                status
                ;;
        restart)
                restart
                ;;
        remote_console)
                remote_console
                ;;
        console)
                console
                ;;
        *)
                echo $"Usage: $0 {start|stop|status|restart|console|remote_console}"
                exit 1
                ;;
esac
exit $RETVAL
